---
title: "HAAM-world-map"
author: "bamorim"
date: "2024-05-30"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries needed:

```{r libraries, message=FALSE}
library(ggplot2)
library(sf)
library(ggspatial)
library(dplyr)
library(ggpubr)
library(stringr)
library(svglite)
```


# Import locations

```{R locations}
library(readr)
loc_summerschool <- read_csv("loc_summerschool.csv")[,1:3]
head(loc_summerschool)
```




# MAP 1 - BLUE OCEAN, WHITE CONTINENTS


## Base-map

```{r base, echo=FALSE}
world=map_data("world")
theme_clean=theme(axis.text = element_blank(),axis.line = element_blank(),axis.ticks = element_blank(),panel.grid = element_blank(),axis.title = element_blank(),legend.position="right",line = element_blank(),title = element_blank(),plot.background=element_rect(fill="#a6bcff"),panel.background = element_blank(),legend.box = element_blank())

```

```{r base-map}
map=ggplot(data = world) + 
  geom_polygon(aes(x = long, y = lat, group = group), 
               fill="white", color = "#c8cac8", size=0.1,alpha=1) + 
  theme_clean
map
```



```{R locs-map}
map2=map + 
  geom_point(aes(x=Long, y=Lat),data=loc_summerschool,shape=21,stroke=0.2,fill="#f4d03f",size=4) +
  coord_sf(xlim = c(-160, 180), ylim = c(-55, 80))
map2
```
```{R save-map, message=FALSE}
ggsave(filename="haam_summer_school_map_bluewhite2.pdf",map2,limitsize=F,device="pdf")
ggsave(filename="haam_summer_school_map_bluewhite2.png",map2,limitsize=F,device="png")
ggsave(filename="haam_summer_school_map_bluewhite2.svg",map2,limitsize=F,device="svg")
```





# MAP 2 - WHITE OCEAN, BLUE CONTINENTS


## Base-map

```{r base2, echo=FALSE}
world=map_data("world")
theme_clean=theme(axis.text = element_blank(),axis.line = element_blank(),axis.ticks = element_blank(),panel.grid = element_blank(),axis.title = element_blank(),legend.position="right",line = element_blank(),title = element_blank(),plot.background=element_blank(),panel.background = element_blank(),legend.box = element_blank())

```

```{r base-map2}
map=ggplot(data = world) + 
  geom_polygon(aes(x = long, y = lat, group = group), 
               fill="#3D5EC1", color = "#c8cac8", size=0.1,alpha=1) + 
  theme_clean
map
```

```{R locs-map2}
map2=map + 
  geom_point(aes(x=Long, y=Lat),data=loc_summerschool,shape=21,stroke=0.2,fill="#f4d03f",size=4) +
  coord_sf(xlim = c(-160, 180), ylim = c(-55, 80))
map2
```
```{R save-map2, message=FALSE}
ggsave(filename="haam_summer_school_map_whiteblue.pdf",map2,limitsize=F,device="pdf")
ggsave(filename="haam_summer_school_map_whiteblue.png",map2,limitsize=F,device="png")
ggsave(filename="haam_summer_school_map_whiteblue.svg",map2,limitsize=F,device="svg")
```




# MAP 3 - WHITE OCEAN, WHITE CONTINENTS, BLUE BORDERS


## Base-map

```{r base3, echo=FALSE}
world=map_data("world")
theme_clean=theme(axis.text = element_blank(),axis.line = element_blank(),axis.ticks = element_blank(),panel.grid = element_blank(),axis.title = element_blank(),legend.position="right",line = element_blank(),title = element_blank(),plot.background=element_blank(),panel.background = element_blank(),legend.box = element_blank())

```

```{r base-map3}
map=ggplot(data = world) + 
  geom_polygon(aes(x = long, y = lat, group = group), 
               fill="white", color = "#3D5EC1", size=0.5,alpha=1) + 
  theme_clean
map
```

```{R locs-map3}
map2=map + 
  geom_point(aes(x=Long, y=Lat),data=loc_summerschool,shape=21,stroke=0.2,fill="#f4d03f",size=4) +
  coord_sf(xlim = c(-160, 180), ylim = c(-55, 80))
map2
```
```{R save-map3, message=FALSE}
ggsave(filename="haam_summer_school_map_whitewhiteblue.pdf",map2,limitsize=F,device="pdf")
ggsave(filename="haam_summer_school_map_whitewhiteblue.png",map2,limitsize=F,device="png")
ggsave(filename="haam_summer_school_map_whitewhiteblue.svg",map2,limitsize=F,device="svg")
```



